version: '3'

services:
  web: 
    container_name: apiSpotify
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links: 
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: myMongoDatabase
    image: mongo
    ports: 
      - "27018:27017"
    logging: 
      driver: none
    command: mongod --quiet --logpath /dev/null 
